name: The Bunker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3592862256336957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.295485008507967
  lightness: 0.24525729450397193
  saturation: 0.6181764805223793
  rhythmicContrast: 0.7802962048444897
purpose: []
